version: 2
groups:
  Software:
    approve_by_comment:
      approve_regex: ^Approved
      enabled: true
      reject_regex: ^Rejected
    required: 1
    reset_on_push:
      enabled: false
    users:
    - AppleDevelops
